name: Format code with Black
  
on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - main

jobs:
  lint:
    name: runner / black formatter
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Install dependencies
        run: |
          pip install black
      - name: Run Black
        uses: wearerequired/lint-action@v2
        with:
          black: true
          auto_fix: true

