name: Python application

on:
  push:
    branches:
      - deploy2

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        if: github.ref == 'refs/heads/deploy2'
        env:
          deploy_url: ${{secrets.RENDER_DEPLOY_HOOK_URL}}
        run: |
          curl "$deploy_url"
